### PR TITLE
Update UI

### LINKED ISSUE #1: Add all options to UI
Sorry, this is a lot. I may have missed something (Don't worry about it)

Please add these all to the UI:

Errors:

Custom 400 html: optCustom400 (default: false, boolean)
400 html location: optCustom400location (default: /400.html, string)
Custom 401 html: optCustom401 (default: false, boolean)
401 html location: optCustom401location (default: /401.html, string)
Custom 403 html: optCustom403 (default: false, boolean)
403 html location: optCustom403location (default: /403.html, string)
Custom 404 html: optCustom404 (default: false, boolean)
404 html location: optCustom404location (default: /404.html, string)
Send 404 variable: optCustom404usevar (default: false, boolean)
404 variable name: optCustom404usevarvar (default: locationoflostuser, string)

Exclude .html:

Exclude .html extension: optExcludeDotHtml (default: false, boolean)
Exclude .htm extension: optExcludeDotHtm (default: false, boolean)

Index rendering:

Auto render index.html (already implemented, don’t change this)
404 instead of directory listing: optDir404 (default: false, boolean)

Directory listing:

Static directory listing (no JavaScript): optStatic (default: false, boolean)
Show dot files in directory listing: optDotFilesDirListing (default: false, boolean)

Other:
Send cache control header with every request: optCacheControl (default: false, boolean)
Cache control header value: optCacheControlValue (default: must-revalidate, string)

Htaccess:

Scan for htaccess: optScanForHtaccess (default: false, boolean) - with this one, please add a place that we can add a link to the htaccess readme 
Allow GET requests: optGETHtaccess (default: false, boolean)
Allow PUT/POST requests: optPUTPOSTHtaccess (default: false, boolean)
Allow DELETE requests: optDELETEHtaccess (default: false, boolean)
Show in directory listing: optDirListingHtaccess (default: false, boolean)

File upload/delete: 

Allow file upload: optUpload (default: false, boolean)
Allow replace file: optAllowReplaceFile (default: false, boolean)
Allow deleting files: optDelete (default: false, boolean)

IP blocking:

Search for IP block list: optIpBlocking (default: false, boolean)
Ip block list location: optIpBlockList (default: ipblock.list, string)
Block requests from undefined addresses: optIpBlockUndefined (default: false, boolean)
Please also add a place to put a link to the readme

Auth:

Use basic auth: optUsebasicauth (default: false, boolean)
Auth username: optAuthUsername (default: admin, string)
Auth password: optAuthPassword (default: admin, string)

Protocol options: (do not do at the moment)

Use https: optUseHttps (default: false, boolean)
Forward to https: optHttp2Https (default: false, boolean)
Use http 2.0: optHttp2 (default: false, boolean)

For https and http 2, please have places where we can generate keys required for protocol (could you please work on the key generation? I plan to use the nodejs `require('https')` and `require('http2')`)

Let me know if you need anything

### LINKED ISSUE #3: Name & Logo
Here's the current name and logo:
image

kzahel gave us permission to use the web server for chrome logo:
image

Do we want to use the web server for chrome logo or a new logo?
I could also make an updated version of the web server for chrome logo to make it look better while keeping its charm.
Let me know what you think @ethanaobrien.

Also, what should we call this? 
It doesn't make sense to use the old "Web Server for Chrome" name because it isn't a chrome app anymore.
I like the name "Simple Web Server". Do you have any other ideas?

### LINKED ISSUE #14: Dark mode UI
Light, dark, or follow system

### PR DESCRIPTION
**Pull request by terreng**
- [x] Add all new options to the ui (Closes #1)
- [x] Add new logo (Closes #3)
- [x] Add confirmation prompt when deleting server

### CODE REVIEW

**Comment by terreng** [comment]
@ethanaobrien What do you think?

logo

**Comment by ethanaobrien** [comment]
I think its cool, but I also think it looks a little too Simple.

**Comment by ethanaobrien** [comment]
Then let's go with that logo

**Comment by ethanaobrien** [comment]
@terreng Have you started adding the new UI options?

**Comment by terreng** [comment]
Yes. I left off working on how to organize them. This is what I have so far (incomplete).

<h1>Basic options</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Enabled | enabled | true/false | - | Whether the server is turned on or not
Directory | path | path string | - | Directory to serve files from
Port | port | number 1 - 65535 | 8080 | Port that server is accessible on
Accessible on local network | localnetwork | true/false | false | Makes the web server accessible over LAN to other computers on the network. Access using this computer's local IP address.

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Basic rules</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Automatically show index.html | showIndex | true/false | true | Automatically serve index.html file when no file path is specified
Single page rewrite (for SPA) | spa | true/false | false | Automatically rewrite all paths that don't match files to index.html in root directory. For Single Page Applications.
Show directory listing | directoryListing | true/false | true | Show a list of files in the specified directory instead of a 404 page

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Error Pages</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Custom 404 error page | custom404 | path string | - | File path to a custom 404 page. Will fallback to default 404 page if value is empty or file does not exist.
Custom 403 error page | custom403 | path string | - | File path to a custom 403 page. Will fallback to default 404 page if value is empty or file does not exist.
Custom 401 error page | custom401 | path string | - | File path to a custom 401 page. Will fallback to default 404 page if value is empty or file does not exist.
Custom 400 error page | custom400 | path string | - | File path to a custom 400 page. Will fallback to default 400 page if value is empty or file does not exist.
Custom error path variable | customErrorReplaceString | string | - | Optionally specify a custom string that will be looked for in your error pages and replaced with the current path. For example, if your custom 404 page included: "The file at {{PATH}} does not exist" and you set this option to "{{PATH}}", when your file is served it would say "The file at /example.txt does not exist".

<h1 style="color: rgb(0, 0, 0); font-family: Times; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Security</h1>

Option | Name | Value | Default | Description
-- | -- | -- | -- | --
Enable HTTPS | https | true/false | false | Make server accessible over a secure connection (https) instead of just http.
Forward http to https | forwardHttpToHttps | true/false | true | Only accessible in the UI if https option is enabled. If the https option is enabled, redirect all insecure (http) requests to https.
Custom HTTPS cerificate | httpsCert | string | - | Not accessible in the UI. Optionally override this option to provide a custom HTTPS certificate.
Custom HTTPS key | httpsKey | string | - | Not accessible in the UI. Optionally override this option to provide a custom HTTPS key.

**Comment by ethanaobrien** [comment]
Ok, cool. To verify, are all the 'name' values the value of the setting in the server config. I can start to translate this over.

Also, when forwarding to https, the http server needs a different port to listen on. Could you give me the name of the variable and then I will start to implement this.

Also, I don't know if I could forward to https from http. What I mean is I don't know if I can easily get the domain name the user is accessing the server through and then give a 301 error pointing toward the https location. Do you know if you can easily forward from http to https without getting the domain name? If we cant resolve this issue we can turn the issue into "also listen on http"

Also, the `Automatically show index.html` option will auto render `index.html`, `index.htm`, `index.xhtml`, and `index.xhtm`

Also, for the `Single page rewrite (for SPA)` I think we should have an option to change the file it renders, like in the original Web Server for Chrome

Please leave your notes

**Comment by terreng** [comment]
I forgot that http and https are on different ports, to the https redirect doesn't make much sense.

I don't think it really makes sense to let the user specify two different ports, one for http and one for https.

I assume the way it works now is that the one port just gets changed to https, which makes sense. We should probably keep it that way.

Those option names are a work in progress, so let's wait until I finish going through and organizing all of them in case I need to change anything.

I agree that the single page rewrite should let you change the filename.

**Comment by ethanaobrien** [comment]
Awesome, thank you, once everything is official I will update the options in the server code.
  
Also, I agree about the https and http thing, the user can just create another server if needed.
  
Just for some info, how the ports work for https and http is that the default http port is 80 and the default https port is 443, which is why you don't see ports in the address bars on websites like google (google supports http and https) there may be an upgrade header, I'll have to look into that.

**Comment by terreng** [comment]
@ethanaobrien I agree that the simplified logo I made looks too simple. So I recreated the old one, but made it, in my opinion, just a little bit less ugly. What do you think? 
web server logo

**Comment by ethanaobrien** [comment]
It looks awesome

**Comment by ethanaobrien** [comment]
@terreng Would you mind if I tried to do a little work on the UI?

**Comment by terreng** [comment]
@ethanaobrien I think it would probably be easier if I did it, seeing as I'm already halfway through. I've also already planned out a few things. I will have time to finish the UI in the next few weeks. Did you have anything particular in mind?

**Comment by ethanaobrien** [comment]
@terreng Ok thats good too. I would like to make it to where we just have an array list of all the options and what values they change. If its ok with you I've gotten a lot better at transferring data between the main process and the window and I could work on that part once youve finished with this

One thing I've found is that with the way it saves at the moment, any custom options not displayed in the ui are overwritten after every save

**Comment by terreng** [comment]
Thanks, I will make sure that is addressed.

**Comment by ethanaobrien** [comment]
@terreng Should we have an offline html version of all the howto files that the user can use if offline, etc? I know there is some software (qemu for example) that does this

**Comment by terreng** [comment]
> @terreng Should we have an offline html version of all the howto files that the user can use if offline, etc? I know there is some software (qemu for example) that does this

Sounds like a good idea. It'll be built in to the program.

**Comment by terreng** [comment]
@ethanaobrien The UI now has all of the options, and is in a usable state. Please feel free to run from this branch and let me know what you think!

> One thing I've found is that with the way it saves at the moment, any custom options not displayed in the ui are overwritten after every save

I've fixed this, thanks.

**Comment by ethanaobrien** [comment]
@terreng Sorry, I've been a little busy. The new UI looks good. Just one question, do you think we should have an option to turn off the last modified date/time header?

**Comment by terreng** [comment]
> @terreng Sorry, I've been a little busy. The new UI looks good. Just one question, do you think we should have an option to turn off the last modified date/time header?

Good idea. How about we just tie it to the show directory listing option? If directory listing is enabled, that info is easily available anyway. If it's disabled, then that info is most likely not desired. What do you think?

**Comment by ethanaobrien** [comment]
@terreng
>Good idea. How about we just tie it to the show directory listing option? If directory listing is enabled, that info is easily available anyway. If it's disabled, then that info is most likely not desired. What do you think?

I meant like as a header, this helps the browser determine if it needs to re-fetch the resource or if it already has it and I have found in some cases that it may cause problems.

**Comment by terreng** [comment]
> @terreng
> 
> > Good idea. How about we just tie it to the show directory listing option? If directory listing is enabled, that info is easily available anyway. If it's disabled, then that info is most likely not desired. What do you think?
> 
> I meant like as a header, this helps the browser determine if it needs to re-fetch the resource or if it already has it and I have found in some cases that it may cause problems.

I knew you were referring to the header. How about we just don't include it.

**Comment by ethanaobrien** [comment]
then on line 1177 in the handlers.js file could you set lastModified to false (Im pretty sure it is true by default so we cant just remove it)

**Comment by ethanaobrien** [comment]
@terreng I'm not sure whats wrong, but there seems to occasionally be a problem when saving a server

**Comment by terreng** [comment]
@ethanaobrien Great catch! That was a pretty big oversight on my part. I've fixed it.

**Comment by ethanaobrien** [comment]
@terreng Cool, I think we're just about ready for a first release!

**Comment by terreng** [comment]
Yep! I'm going to clean up the UI a little bit, but I'll save dark mode for later. I also need to fix the issue of catching errors properly, and add in the update check.

Once that's done, I'll get our website up and running and we can put a download on there.

**Pull request merged**
