### PR TITLE
Fix error messages

### LINKED ISSUE #55: IP changing
What happens if the local network IP changes while the program is running? This should trigger an event to restart the servers and send a message to the UI with the new IP.

### LINKED ISSUE #59: Blank page
I'm getting a blank page at `/` with this combination of options.

Screen Shot 2022-01-23 at 4 22 30 PM

Screen Shot 2022-01-23 at 4 23 05 PM

Screen Shot 2022-01-23 at 4 23 12 PM

### PR DESCRIPTION
**Pull request by ethanaobrien**
Resolves #55
Closes #59

### CODE REVIEW

**Review by terreng — DISMISSED** [review]

**Comment by ethanaobrien** [comment]
@terreng Do you want me to go ahead and add my fix for #55 into this pr?

**Comment by terreng** [comment]
> @terreng Do you want me to go ahead and add my fix for #55 into this pr?

Sure

**Comment by terreng** [comment]
@ethanaobrien Want to merge or add a fix for #59 to this pr?

**Comment by ethanaobrien** [comment]
I'll add a fix for #59 dont merge yet

**Comment by terreng** [comment]
It might be a good idea to do a little bit more testing on all of the options to catch any remaining bugs before release.

**Comment by terreng** [comment]
@ethanaobrien I'm going to try and have the website ready to go soon. I'm not going to add any more features for the initial release. I'm hoping to get the initial version released soon, so we can tell people who use the Web Server for Chrome extension about it. Then I'll work on adding more features to the next version (1.2). Let me know if there's anything else that we should do before release!

**Comment by terreng** [comment]
@ethanaobrien I'm planning on having the website up soon. I'm not going to add any more features to the app before the initial release. I'm hoping to release soon so we can tell people who use the Web Server for Chrome extension about it. Hopefully we can add a message to the old app with a link, and ask kzahel to push out the update.

Here's what I'm thinking:
"Chrome apps are going away! Web Server for Chrome is now a standalone program: https://simplewebserver.org/"

After initial release, I'll work on adding more features for the next version (v1.2).

Let me know if there's anything else that we should do before release!

**Comment by ethanaobrien** [comment]
Sorry I  havent been able to work much. I kind of already have that. (https://github.com/ethanaobrien/web-server-chrome/blob/master/react-ui/js/index.js#L578) I will just need to change the link.

https://github.com/kzahel/web-server-chrome/pull/264

**Comment by terreng** [comment]
@ethanaobrien Any update on this?

**Comment by ethanaobrien** [comment]
Sorry, not yet, I should have time to work on this next week

**Comment by ethanaobrien** [comment]
@terreng Sorry for this taking so long. I've finished

**Review by terreng — APPROVED** [review]

**Pull request merged**
