### PR TITLE
Update https instructions

### LINKED ISSUE #43: HTTPS documentation
@ethanaobrien Could you please create some basic documentation on how to set up the HTTPS feature for someone who has never used it before? 

Here's a screenshot of what the UI looks like currently.
Screen Shot 2021-12-30 at 5 23 47 PM

Do the auto-generated certs also work on the local network or just localhost?

### PR DESCRIPTION
**Pull request by ethanaobrien**
Make sure, when setting the value of the input element, that you replace all `\r` with `\\r` and `\n` with `\\n`. Also when saving, please be sure to do the opposite

Closes #43

### CODE REVIEW

**Comment by terreng** [comment]
What good is the auto generated certificate feature if the browser still shows the URL as insecure? What does the user have to do to make it work?

**Comment by ethanaobrien** [comment]
A custom generated script is often for testing. A not user generated certificate often costs money and we cannot supply.

You can click advanced and then click continue on the new tab page or (you might wat to add this to the UI documentation) you can type `thisisunsafe` while on the insecure page and it will load

**Comment by terreng** [comment]
> you might wat to add this to the UI documentation

Please add everything relevant to the documentation file. The UI documentation is going to consist of option descriptions from howTo/options.html, and any relevant readme files there.

**Comment by ethanaobrien** [comment]
So, would you like me to rewrite the markdown file into html?

**Comment by terreng** [comment]
> So, would you like me to rewrite the markdown file into html?

Sure, but I don't mind converting it later myself.

Please add an explanation of how to use the auto generated certs in the browser.

**Comment by ethanaobrien** [comment]
@terreng Just updated, sorry for the delay. Anything else I need to add?

**Comment by terreng** [comment]
The auto generated certificates don't have newlines. Is this a problem?

Also, I got this error when enabling https, clicking the generate crypto button, and then saving a server.

Screen Shot 2022-01-16 at 2 24 23 PM

**Comment by ethanaobrien** [comment]
@terreng 

>The auto generated certificates don't have newlines. Is this a problem?

Yes, this is a problem, it makes the newlines when generating, does this problem occur when reading from the text input value?

**Comment by terreng** [comment]
@ethanaobrien It looks like I didn't follow your instructions properly. I've fixed it.

**Review by terreng — APPROVED** [review]

**Pull request merged**
