### PR TITLE
https / bug fixes / secutity

### LINKED ISSUE #7: https

### LINKED ISSUE #22: Consistent response error format
I think we should use the following standard format for http errors:

Error 404: Not Found
Error 403: Forbidden
Error 500: Internal Server Error

etc.

### LINKED ISSUE #23: Move mime types to separate mimetypes.json file
This should help reduce clutter in WSC.js

### PR DESCRIPTION
**Pull request by ethanaobrien**
Resolves #7
Resolves #23 
Resolves #22 

https Will auto generate crypto / cert if not found in config - Will save generated crypto

MANY major bug fixes

Found how to catch server listen error

https option is literally just `https` (`serverconfig.https`)

Ask me if you have questions

### CODE REVIEW

**Comment by terreng** [comment]
So, `https` instead of `optUseHttps`?
And `key` and `cert` for custom https certs?

Does it catch invalid keys/certs if the user enters something wrong?

**Comment by ethanaobrien** [comment]
@terreng Correct, although the server will auto generate the cert/key if none if found or when the server is created. Changes will be saved to `config.json`. I do not recommend putting the key and cert options into the UI - As everything is handled in the backend

**Comment by terreng** [comment]
So should there be an option for the user to provide a custom cert or no?

**Comment by ethanaobrien** [comment]
@terreng We could, I dont see why someone would need to do so, doing this may open the server to not being able to start due to the key being inputted even a little wrong. What do you think?

**Comment by terreng** [comment]
We could also have this as an option just not in the UI, and we could have a guide on how to manually put a custom cert in the config file. If it's not something that people will do very often, then I think this makes sense. Want to go with that?

**Comment by ethanaobrien** [comment]
@terreng I like that idea. Should I write it in a read me or put it in the website for when we make it

**Comment by terreng** [comment]
You can make a new page in the howTo folder. It will be easy to convert everything to the website once it's ready.

**Comment by terreng** [comment]
I think we should rename `cert`  and `key` to `httpsCert` and `httpsKey`.
I notice that you run the same piece of code to generate certs and keys, once when the user saves, and once when servers start. I think you should make this a function that takes the array of servers as input.
Also, please remove the temporary `arg1.servers[i].https = true`

**Comment by ethanaobrien** [comment]
>I notice that you run the same piece of code to generate certs and keys, once when the user saves, and once when servers start. I think you should make this a function that takes the array of servers as input.

I don't quite understand what you're saying. I made it to where when the config saves it will generate key and cert as needed. I also put it when the server starts to make sure (mainly when testing) if the https is enabled, but there is no key/cert in the config it will generate and save the key/cert

I will make other changes when I get a chance

**Comment by terreng** [comment]
What I meant by create a function is do something like this so you aren't repeating code.
```js
function setMissingCrypto(servers) {
    for (var i=0; i<servers.length; i++) {
        if (servers[i].https) {
            if (!servers[i].cert || !servers[i].key) {
                var crypto = WSC.createCrypto()  // Create HTTPS crypto
                servers[i].key = crypto.privateKey
                servers[i].cert = crypto.cert
            }
        }
    }
}
```

**Comment by ethanaobrien** [comment]
@terreng All done and ready to merge!

**Comment by terreng** [comment]
Add the macOS save location to the how to: `$HOME/Library/Application Support/Simple Web Server/config.json`

The point of moving the crypto thing to a function was so that you aren't repeating it twice, which it looks like you still are. If the function doesn't solve that, then there's no point.

For the errors, I think we should use this format:
```html
<h1>Error 500: Internal Server Error</h1>
<p>Error with your script, check the logs</p>
```

I think you should update the error function to only take the message part in the `defaultMsg` argument, and then use the status code to determine what the primary error message should be.

For example, you would call `this.error("Error with your script, check the logs", 500)` and it would output the HTML above.

**Comment by ethanaobrien** [comment]
I would prefer to use `<h1>500 - Internal Server Error</h1>` rather than `<
h1>Error 500: Internal Server Error</h1>` because I don't feel the need to
put error at the beginning (Because that is what the error message is for)
Could I do this?

Also, the reason I repeat executing the code twice is for a failsafe, when
there is an error saving and the crypto didn't save - It generates a new
one and starts the server

**Comment by terreng** [comment]
> I would prefer to use `<h1>500 - Internal Server Error</h1>` rather than `< h1>Error 500: Internal Server Error</h1>` 

That works!

I understand why you're running the code twice. Because you're doing the same thing in two places, using a function would mean you only need to update this in one place instead of two in the future. But it's not a big deal. What you have works.

**Comment by ethanaobrien** [comment]
@terreng Go ahead and merge

**Comment by terreng** [comment]
Could you add the macos save location to `howTo/custom https cert&key.md` real quick?
`$HOME/Library/Application Support/Simple Web Server/config.json`

**Comment by ethanaobrien** [comment]
@terreng done

**Review by terreng — APPROVED** [review]

**Pull request merged**
