### PR TITLE
Check for gz or br file before sending 404 response

### LINKED ISSUE #219: Missing Content-Encoding: gzip Header for Files with .gz Extension
**Description/Steps to reproduce**
The Content-Encoding: gzip header should be included even when the file extension already contains .gz, but it is currently missing, causing the functionality to fail.

**Version information**
Windows, macOS, or Linux?
  MacOS
What version of the program are you using?
  Version 1.2.12 (31)

**Screenshots**
If applicable, add screenshots to help explain the issue.
image

### PR DESCRIPTION
**Pull request by ethanaobrien**
Resolves #219 . This removes the `this.opts.precompression` option

### CODE REVIEW

**Comment by terreng** [comment]
Thanks for this quick PR. I tested this and I think it's still not quite right.

If I have `example.js.gz`, then loading `example.js` works as expected (mime type js, served w/ gzip). However, loading `example.js.gz` directly doesn't work as expected (mime type gz, no content encoding header).

I think that loading `example.js.gz` should serve w/ mime type js, content encoding gzip.

Based on the Unity example in #219, I can see that it's trying to load `Build/WebGL.framework.js.gz` as a script, but that's not working because the script is being returned w/ the wrong headers.

I looked up the Unity documentation for web servers to confirm that I'm understanding this correctly. [Here's what I found.](https://docs.unity3d.com/Manual/webgl-server-configuration-code-samples.html)

They specifically recommend that web servers add a special case for `.js.gz` files:

```
# On-disk Brotli-precompressed JavaScript code files:
location ~ .+\.js\.br$ {
    gzip off; # Do not attempt dynamic gzip compression on an already compressed file
    add_header Content-Encoding br;
    default_type application/javascript;
}
```

So to fix this, we could either:
1. Add a special case just for .js.gz files
2. (I would prefer this) Extend the same behavior to any file with a double extension ending in .gz. (The way I would test for this is removing the .gz and checking if the file still has a recognized extension or not. That way, files like `example.gz` still serve with gz mime type, but files like `example.css.gz` serve with mime type css.

I don't think that doing this is going to mess things up for anyone, since if you have a file with a double extension like `.js.gz`, this is probably what you want to happen.

**Comment by ethanaobrien** [comment]
This logic has been corrected

**Comment by terreng** [comment]
Do you think we should remove the option entirely, or keep it and just have it turned on by default? (So instead of checking if it's true, check if it's not false.)

I'm trying to think of if there's ever a time when you wouldn't want it to work this way.

**Comment by ethanaobrien** [comment]
If you'd like, we can add it back and have it enabled by default?

**Comment by terreng** [comment]
Yeah, how about add it back but have it check `this.opts.precompression !== false`

**Comment by ethanaobrien** [comment]
@terreng This change has been made, please be sure to test before merging

**Comment by terreng** [comment]
I tested it and this seems to work perfectly! One more question for you: as far as I can tell `node-blob` isn't actually used. Can I remove that dependency?

**Comment by ethanaobrien** [comment]
Yep, I just checked and I couldn't find any uses of Blob. You can go ahead and remove it

**Pull request merged**
