### PR TITLE
Modern JS Syntax & Plugins

### PR DESCRIPTION
**Pull request by ethanaobrien**
- Use classes instead of modifying the prototype
- Use `let` and `const` instead of `var`

Why:
- `var` is function scoped, which can consume more memory.
- I think its time to go forwards.

This pr is not ready! It may not even work (I'm just editing it right now, and not testing before I push).

Note: This pr includes the fixes/improvements from #98 (for the FileSystem and handler files only)

### CODE REVIEW

**Comment by terreng** [comment]
Thanks for your continued work on this project! What do you think about the idea to rewrite in Rust? While I still think we could offer two versions of the program (Rust vs node backend) with the same front-end UI, I just don't want you to spend too much of your time optimizing the JavaScript code if the plan is to convert it to Rust soon. What do you think?

**Comment by ethanaobrien** [comment]
As you kind of said, I think that while we should offer a more lightweight rust version, a "lite" version of the app, but at the same time I think we should also offer this version for people looking for more features. There are some features (like server side scripts) that would probably not be supported in rust. What do you think.

Also, I've found a lot of bugs while re-writing the handler file, so this update should speed up the server at least a bit

**Comment by terreng** [comment]
I think supporting both versions is a good idea. That said, we don't know yet if it would be possible to provide plugins and server side scripts for the Rust version. It actually might be, but we'll have to try it and find out.

Good to know that this pr will contribute to the stability of the current app. Thanks!

I'm going to focus more on the Rust / Tauri version going forward. I'll try and find the time to build a prototype version of the app with Tauri, and then we can work from there.

**Comment by ethanaobrien** [comment]
Sounds good.

Do you want me to merge #98 into this pr? This would make it much easier especially to merge (because of merge conflicts)

**Comment by terreng** [comment]
> Do you want me to merge #98 into this pr?

Sure thing! Please proceed.

**Comment by ethanaobrien** [comment]
Awesome, I'll do so probably tomorrow. Thank you!

**Comment by ethanaobrien** [comment]
Hey @terreng do you think we should make the simple web server project into an organization if we're going to have separate repos for this version and the rust version. This way we could also separate the website into its own repository

**Comment by terreng** [comment]
> do you think we should make the simple web server project into an organization

That might be a good idea, but I'm not sure yet! Once I get around to setting up the Tauri project, I'll see how many files are shared between both versions. Having them in the same repo might end up making it easier to avoid updating things in two places.

**Comment by ethanaobrien** [comment]
I've re-written/cleaned up the entire app. Could you do some testing when you can?

**Comment by terreng** [comment]
Feel free to add the tray feature for Windows. Just the app icon in the tray, and clicking it opens the program, right? Global setting called `tray`. Make it its own PR.

**Comment by ethanaobrien** [comment]
> Okay. This includes plugins too, right?

Yes, the backend to the plugins is included. If you need me to write the frontend I can try that, let me know.

> Make it its own PR.

The tray is actually already implemented (see line 166 in the index.js file in the main branch) the option just needs to be added to the Ui. Would you like me to do this?

**Comment by terreng** [comment]
Next week. My plan is to merge this, add the UI for plugins, and do a release. As well as build a prototype Tauri version of the app.

Is this code ready to ship?

**Comment by ethanaobrien** [comment]
I've tested most parts of the app, including most of the htaccess features. I've fixed everything I can find. You might want to do some testing too and let me know if you find anything.

In short, the code should be ready. I'll do some final testing probably tomorrow or Wednesday to make sure there aren't any remaining bugs.

**Comment by ethanaobrien** [comment]
Using `===` or `!==` is much much better practice (it's equal to `==` in pretty much every other language). You're comparing a variable that was undefined to null, and for some reason it was returning true. I think we could replace it with `editIndex !== undefined` assuming you don't define those values as null anywhere. This is why I changed that to that it is

**Comment by terreng** [comment]
I deliberately chose `!= null` because it checks for both `null` and `undefined`. The new code has the exact same behavior, but is more complicated. So why not use the shortcut?

**Comment by ethanaobrien** [comment]
That is true now that I think about it. I'll change it to `!= null` when I can. Sorry about that

**Comment by terreng** [comment]
Sounds good. It's obviously not a big deal, just a stylistic preference. Once you finish that, I'll approve so you can merge when ready, as long as there isn't anything else to fix.

**Comment by ethanaobrien** [comment]
@terreng Sorry for the delay, this is done!

**Review by terreng — APPROVED** [review]

**Pull request merged**
