### PR TITLE
Bug Fixes

### LINKED ISSUE #39: ssl cert weirdness
I was unable to get the 1.0 build to work with SSL.  I built from https://github.com/terreng/simple-web-server/commit/9a76b8b90f7bcacb4039576cc9cd359c09e5b45d and still no joy. 
I noticed the key/cert info was getting parsed incorrectly from config.json

adding this transformation worked as a band-aid for me: (index.js):
```
		let [key,cert] = ( ({httpsKey,httpsCert})=>{ return [httpsKey,httpsCert]})(serverconfig); 
		[key,cert] = [key,cert].map( value=>{
                      return value
			.replaceAll(/(?<!(BEGIN|RSA|PRIVATE|END))[ ]/g,'\n')
			.replace(/-[^-]+$/,'');
                 });	    
		var server = https.createServer({key, cert}); 
               // var server = https.createServer({key: serverconfig.httpsKey, cert: serverconfig.httpsCert});
```

(i don't think it's the right way to solve this so I didn't create a PR)

### PR DESCRIPTION
**Pull request by ethanaobrien**
Don't merge. Just let this build up. Although, we will merge before the first release

TODO
- [x] Rename all options in WSC files
- [x] `wsc.htaccess` to `.swshtaccess`
- [x] check for `.html` and `.htm` files when excluding `.html` extension
- [x] ignore everything in a directory that starts with a period
- [x] Auto block requests from undefined ip addresses
- [x] Add `ipThrottling` option
- [x] Remove option to allow requests to htaccess files

Resolves #39

### CODE REVIEW

**Comment by ethanaobrien** [comment]
TODO: Catch not found error in `httpRequest` function.

**Comment by ethanaobrien** [comment]
@terreng what do you think of the new method of the fs I have been writing. I have started converting the handlers file and it has been much neater. (I did have some trouble committing changes

**Comment by terreng** [comment]
I took a quick look at the files and it looks like you've made quite a few changes. I see you made some things async in the handlers.js file. Let me know if there's anything specific I should look over. Good work!

**Comment by ethanaobrien** [comment]
@terreng Is the way I rewrote the console fine?

**Comment by terreng** [comment]
@ethanaobrien Yes, it looks fine! Assuming it works.

**Comment by ethanaobrien** [comment]
@terreng I think we should have connection throttling per ip as a security feature. Do you think we should do 10 or 5 connections as default. I think we should also put this into the UI (0 will be unlimited connections)

**Comment by terreng** [comment]
> @terreng I think we should have connection throttling per ip as a security feature. Do you think we should do 10 or 5 connections as default. I think we should also put this into the UI (0 will be unlimited connections)

That sounds like a good idea. Let's have the option name be `ipThrottling`.

**Comment by ethanaobrien** [comment]
@terreng Cool, Can you make sure that the input user value is an integer, not double or float. (Whole number, no decimals)

**Comment by terreng** [comment]
> Cool, Can you make sure that the input user value is an integer, not double or float. (Whole number, no decimals)

Will do.

> and one more question. Would you mind if I sent you a simple thing I wrote using the server side javascript and could you look for any security vulnerabilities (ways to overwrite file, ways to read file contents, ways to read htaccess contents/get execution key).

If you're talking about code that is part of the program, then sure.

**Comment by ethanaobrien** [comment]
[New folder.zip](https://github.com/terreng/simple-web-server/files/7772230/New.folder.zip)

The files work with the latest version of the web server at the moment

**Comment by terreng** [comment]
What would we consider a security vulnerability here? If htaccess and file upload were enabled, it would probably be possible to overwrite the file and have it run something else. However, I feel that once you use the server-side javascript feature, all bets are off. So, at the moment I'm not worried about any security vulnerabilities that may be possible when the `htaccess` option is enabled. However, there should definitely not be any vulnerabilities possible when the option isn't enabled.

**Comment by ethanaobrien** [comment]
This is very very true. Although, access to an htaccess file is blocked even with the htaccess feature not on. 

One thing I need to fix is that if the htaccess feature is blocked, the user can view the source of and server side js/post files and will be able to overwrite them (if enabled). Although it is assumed that if you are using the feature that you have the setting on.

**Comment by terreng** [comment]
> One thing I need to fix is that if the htaccess feature is blocked, the user can view the source of and server side js/post files and will be able to overwrite them (if enabled). Although it is assumed that if you are using the feature that you have the setting on.

If the htaccess feature isn't enabled, then all the files should just be treated as regular files. There's nothing to fix.

**Comment by ethanaobrien** [comment]
@terreng I'm having trouble finding how to detect if a file is hidden on windows. Could you try to find something

**Comment by terreng** [comment]
> @terreng I'm having trouble finding how to detect if a file is hidden on windows. Could you try to find something

It looks like it can be done with this: https://www.npmjs.com/package/hidefile

However, I'm starting to think that just ignoring dot files is good enough. It seems unnecessary to add this just for Windows hidden files.

Also, your code also ignores everything in a directory that starts with a period as well, right?

**Comment by ethanaobrien** [comment]
>It looks like it can be done with this: https://www.npmjs.com/package/hidefile

I'll take a look at this. Seems like its possible

>However, I'm starting to think that just ignoring dot files is good enough. It seems unnecessary to add this just for Windows hidden files.

Yea, It would be really difficult (and inefficient) to implement this especially to check all parent directories

>Also, your code also ignores everything in a directory that starts with a period as well, right?

Not yet. I'm going to have to fix this.

**Comment by terreng** [comment]
> Yea, It would be really difficult (and inefficient) to implement this especially to check all parent directories

Let's just only do dot files. The regex in this answer might help: https://stackoverflow.com/a/37030655/6276471
Here is a great tool for understanding regex strings: https://regexr.com/

**Comment by ethanaobrien** [comment]
@terreng Is there anything else I need to work on?

**Comment by terreng** [comment]
> @terreng Is there anything else I need to work on?

Are all of the options fully implemented as described [here](https://github.com/terreng/simple-web-server/issues/1#issuecomment-1000008005)? Including option names, and the fact that `hiddenDotFilesDirectoryListing` only takes effect when `hiddenDotFiles` is enabled?

**Comment by ethanaobrien** [comment]
Yes, I just fixed the last thing

**Comment by terreng** [comment]
> Yes, I just fixed the last thing

Great! Then I don't think there's anything else. Is this ready to merge?

**Comment by ethanaobrien** [comment]
>Great! Then I don't think there's anything else. Is this ready to merge?

Yep, I think so.

**Review by terreng — APPROVED** [review]
Great work!

**Pull request merged**
