### PR TITLE
Update lang.js

### PR DESCRIPTION
**Pull request by mgxy0**
+ italian

### CODE REVIEW

**Comment by mgxy0** [comment]
I'm happy to help!

**Review by stokito — APPROVED** [review]

**Review by mgxy0 — COMMENTED** [review]
fix the last part of IT lang

**Comment by terreng** [comment]
Thanks for your contribution! Could you also provide a translation for the following text for our website? You can just leave it as a comment here.

> Create local web servers in just a few clicks with an easy-to-use interface.
> 
> Easy to configure
> Change server options with just a few clicks.
> 
> Run multiple & in the background
> Run multiple web servers at the same time, even when the app is closed.
> 
> Single Page Applications
> Enable mod rewrite for SPAs with a single click.

**Comment by mgxy0** [comment]
Sure!! I am very happy with your request @terreng 
If you need anything else don't hesitate to ask!!

{

Crea server web locali in pochi clic con un'interfaccia facile da usare.

Facile da configurare
Modifica le opzioni del server con pochi clic.

Esegui multipli in background
Esegui più server web contemporaneamente, anche quando l'applicazione è chiusa.

Applicazioni a pagina singola
Abilita la modifica del modulo per le SPA con un solo clic.

}

**Comment by terreng** [comment]
Thank you for your translation! This is now released in version 1.2.11.

**Pull request merged**
