### PR TITLE
Implements proxy mode and fixes critical bug

### LINKED ISSUE #9: Proxy
I will do this. I already have some of the code written. This option will ignore ALL other options (Except port and local network)

### PR DESCRIPTION
**Pull request by ethanaobrien**
options added:
`adultContent`: will block adult sites from being proxied (only works when pulling from the server, not when using computer proxy settings)
`torrent`: will allow/block streaming torrent files (also only works when pulling from server)
`proxy`: enable/disable the proxy server

Closes #9 

Most other options are ignored by the proxy. it only needs these options (in addition to the ones above)

localnetwork, port, and https

### CODE REVIEW

**Comment by terreng** [comment]
Is the "critical bug" fix the changes to [WSC/FileSystem.js](https://github.com/terreng/simple-web-server/pull/83/files#diff-bb255a7ce28e9b9a9af3ddbb5c04261c4b196c32023847918db70c87cff524e2)?

**Comment by ethanaobrien** [comment]
yes

**Comment by terreng** [comment]
I'm going to cherry-pick just that fix for now. It would be helpful if you could create a separate pr with just the fix.

I appreciate your work on this new proxy feature. I'm probably going to let this pr wait until after the initial release because I am really behind on that. Sorry about that by the way.

**Comment by ethanaobrien** [comment]
>I'm going to cherry-pick just that fix for now. It would be helpful if you could create a separate pr with just the fix.

will do

>I appreciate your work on this new proxy feature. I'm probably going to let this pr wait until after the initial release because I am really behind on that. Sorry about that by the way.

its all good

**Comment by terreng** [comment]
What's the use case for this feature, and how does it work?

**Comment by ethanaobrien** [comment]
Its a boolean variable. The purpose is for the user to go into settings and set the proxy url to the server and all requests will go through the proxy. When performing a get request toward the server it uses a proxy feature I wrote to render a proxy. You can enable the feature and try it out if you want

**Comment by terreng** [comment]
Okay, so correct me if I'm wrong, but here is my understanding: On one computer, you create a new proxy server with the app. On another computer, you go into system settings and configure a web proxy url with the IP address and port. Then, all network requests for the second computer will be routed through the app on the first computer. Is that right?

**Comment by ethanaobrien** [comment]
Correct.

**Comment by terreng** [comment]
What is the use case for this feature? Why would someone want to do this?

**Comment by ethanaobrien** [comment]
There are several proxies out on the internet. It's pretty much like a vpn, redirecting all your traffic through the server. Someone might use it to connect to their home internet from McDonald's or something. This adds a simple button that will allow you to use this feature. Even if it isnt common, its already done and pretty cool with that.

**Comment by ethanaobrien** [comment]
@terreng Ive done testing, this is ready

**Comment by ethanaobrien** [comment]
@terreng ok, this is done and ready to merge

Also, note, you might want to update node (mine was outdated). If it is outdated it might not recognize the lockfile format.
I updated from node version 14 something to node version 18.1.0 (its a lot cleaner in my opinion)

**Pull request closed without merging**
