### PR TITLE
More translations

### PR DESCRIPTION
**Pull request by stokito**
#124

### CODE REVIEW

**Comment by terreng** [comment]
Thank you so much for translating to Russian!! Thanks also for catching all of those typos.

I noticed that just a few of the strings were left untranslated. Would it be possible for you to translate these too?

- ipThrottling_invalid
- option_cacheControl_description
- option_excludeDotHtml_description
- option_spa_description
- remove_plugin_confirm_description
- add_plugin_failed_description
- setting_plugins_description
- setting_tray_description

**Comment by terreng** [comment]
I think they're important. Would you be able to translate them? If not, I'll just use Google Translate.

**Comment by stokito** [comment]
@terreng done, pls merge

**Comment by stokito** [comment]
@terreng I added the missing translation and added README_ru.md.
Here is the text that you asked to translate
```
Создавайте локальный веб-сервер в несколько кликов с помощью простого интерфейса.

Простота настройки
Настройки сервера можно менять под себя в несколько кликов.

Множество веб-серверов в фоновом режиме
Запускайте несколько веб-серверов одновременно, даже когда приложение закрыто.

Одностраничные приложения
Легко можно включить перенаправление запросов для одностраничных приложений Single Page Applications (SPA).
```

**Comment by terreng** [comment]
@stokito Thank you for your contribution! We just released version 1.2.7 which adds Russian. The update is available now on our website and will be available from the Mac App Store and Microsoft Store soon. Thanks again!

**Comment by stokito** [comment]
Thank you, on the website left some untranslated text:

* `Download`: `Скачать`
* `Documentation`: `Документация`
* `Made with ❤️ by @terreng and @ethanaobrien`: `Сделано с любовью авторами @terreng и @ethanaobrien`.
* `A continuation of Web Server for Chrome by @kzahel.`: Это продолжение почившего Web Server for Chrome от @kzahel
* `Chinese translations by @antnesswcm.`: `Перевёл на китайский @antnesswcm`

I don't feel like my name is needed to be added for the Russian translation.

**Comment by terreng** [comment]
Thanks for providing those translations!

> I don't feel like my name is needed to be added for the Russian translation.

Would you like me to remove the credit from the website?

**Comment by stokito** [comment]
no I just mean that it makes no sense to add a similar text "Russian translation by stokito". It's anyway can be seen on github and many others may contribute so it will be outdated.

**Comment by terreng** [comment]
Would you like to be credited on the website or not?

**Comment by stokito** [comment]
no

**Comment by terreng** [comment]
Thanks for clarifying. I'll remove it.

**Pull request merged**
