### PR TITLE
Fixed an unclosed tag and Optimize the language presentation

### PR DESCRIPTION
**Pull request by antnesswcm**
@terreng 
I tried to understand VuePress and added some Chinese translations for the "website" (there are still many unfinished). 
I set up a“Website” locally and previewed the translation, which is available
image
image

### CODE REVIEW

**Comment by terreng** [comment]
This is fantastic, thank you very much! Even though it is unfinished, you have translated the most important pages. I'm going to merge this pull request so that your translations will go live on the website. Please feel free to open a new pull request if you want to make any more changes!

**Comment by antnesswcm** [comment]
I am translating and have finished a lot, which also makes me more familiar with Simple Web Server

**Comment by terreng** [comment]
I added one more string in lang.js because I forgot it:
```js
"web_server_url": "Web server URL"
```

Could you add this and translate it too?

Also, at the bottom of the page `zh-CN/index.md`, could you add and translate this text?

```html
<div>Chinese translations by <a href="https://github.com/antnesswcm" target="_blank">@antnesswcm</a>.</div>
```

**Comment by antnesswcm** [comment]
```"web_server_url": "Web server URL"```
This doesn't need to be translated into Chinese (there is no difficulty in understanding), and it's not good looking, like this "Web 服务 URL" 
```
<div>中文简体翻译 by <a href="https://github.com/antnesswcm" target="_blank">@antnesswcm</a>.</div>
```

**Comment by antnesswcm** [comment]
image
If necessary, please remember to update the Chinese version of these pictures, or you can teach me how to take such beautiful screenshots. I use Windows

**Comment by terreng** [comment]
Okay, thanks for explaining that "Web server URL" does not need to be translated.

Sure thing! I will update the Chinese version of the screenshots.

**Comment by terreng** [comment]
By the way, please don't bother translating anything in the "Advanced Guides" section, because those will probably be updated/removed.

**Comment by terreng** [comment]
I see that you worked on translating more pages. Please feel free to make a new pull request once it's ready!

**Pull request merged**
