### PR TITLE
Fixes - Release 1.1.4

### PR DESCRIPTION
**Pull request by terreng**
- [x] macos: test upgrading/downgrading (overwriting with dmg)
- [x] macos: fix files not serving
- [x] macos: app store languages should only be English (1.1.2+)
- [x] windows: fix icon sizes
- [x] both: fix rtl messing up path
- [x] macos: doesn't retain folder permission on restart (After SSB support added)
- [x] macos: detect sandbox missing permission to access file error
- [x] macos: fix bookmarks not working

Ethan TODO:
- [x] Add error catching where needed (and address hanging issue)
- [x] Address C:/ "error" files
- [x] Add Security-Scoped Bookmarks helper functions to filesystem

### CODE REVIEW

**Comment by terreng** [comment]
@ethanaobrien I'm running into an issue in the Mac App Store build where files won't load. The symptoms are nearly the same as here: https://github.com/terreng/simple-web-server/issues/59#issuecomment-1068598821

The directory listing works fine and shows the files. If I try a url for a file that doesn't exist, I get a 404 error just fine. However, when I try to load a file that does exist, it hangs forever and never loads.

This issue has to do with app sandboxing on macOS. I know you're probably not familiar with how that works, and that's okay. I should be able to figure this out, but what's making it difficult is the way the loading hangs. [Last time the issue was an unhandled promise rejection.](https://github.com/terreng/simple-web-server/issues/59#issuecomment-1074588280) I'm guessing the hanging is a similar problem this time too.

The web server code should be able to handle errors and system calls failing everywhere. An error shouldn't cause it to just hang indefinitely. Could you go through the web server code and make sure you are handling all errors and using .catch on all promises?

**Comment by ethanaobrien** [comment]
Yeah, I’ll go through and do that. Now that I think about it I am pretty sure I didn’t put any error catching around the part where we send the file (where it handles the file streams). Not entirely sure about what could be wrong. Does the fs documentation mention any differences in the create read stream function on macos?

**Comment by terreng** [comment]
> Does the fs documentation mention any differences in the create read stream function on macos?

The issue is related to app sandboxing on macOS. The non-app store version works fine. So it's probably something permission related. It would be a lot easier to debug if all error messages are caught and logged.

**Comment by terreng** [comment]
@ethanaobrien I've just run into the exact same issue on a non-mac app store build of the app, so it might not actually be related to sandboxing after all. I'll be able to determine what the error is once you go though and make sure all possibilities for errors are caught and logged. It would be great if you could make a new pr for this. Keep me updated.

**Comment by ethanaobrien** [comment]
I’ll go through and add that today assuming I have time

**Comment by terreng** [comment]
@ethanaobrien I determined the cause of this particular issue, which I fixed in [19f0208](https://github.com/terreng/simple-web-server/pull/93/commits/19f020853320c6b6b9a1aeaf32e925ff9c5294f8). I just had to remove this part from handlers.js:
```
this.req.on("close", function() {
    stream.close();
})
```

For whatever reason, this close event was being called before the stream started. This then closed the stream, so the response was never served. I was unable to determine what was causing it. This issue ended up being not specific to the mac app store build. I think what caused it is that I upgraded electron from 13 -> 19.

I think you should be able to replicate the issue by building off of the `new-ui` branch and uncommenting that part. You might have better luck figuring it out than I did.

Either way, it would still be great if you could make sure errors are generally handled appropriately anywhere they're not already.

**Comment by terreng** [comment]
@ethanaobrien There's a somewhat related problem. When the app doesn't have permission to read a directory (this happens on the mac app store version if the user hasn't granted permission to a path yet), the web server hangs indefinitely when trying to load `/`, and returns a 404 error when trying to load any other path. I'm not sure if the 404 is because macOS actually pretends like the file doesn't exist, or because that's just how the app interprets the error. But the indefinite hanging thing should never happen, and just shouldn't be possible no-matter what error occurs.

**Comment by ethanaobrien** [comment]
>I think what caused it is that I upgraded electron from 13 -> 19.

Do you think we should open an issue in the electron repository?

>Either way, it would still be great if you could make sure errors are generally handled appropriately anywhere they're not already.

I’ll do this when I can. I’m going to be out of town for about a week so I won’t be able to work on anything

I’ll work on the hanging issues. I have some fixes in mind and will work on them when I get a chance


In the bug you mentioned, when it has a 404 error on any other path does the any other path you requested actually exist or even if it had permission would it show as 404?

**Comment by terreng** [comment]
> Do you think we should open an issue in the electron repository?

I'm not sure how the issue with the web server in node could be related to Electron, but that's the only clue I have. I think we should try and figure out the cause of the issue first.

> I’ll do this when I can.

Sounds good 👍

I'm probably going to fully release version 1.1.1 on both stores and the website within the next few days!

> In the bug you mentioned, when it has a 404 error on any other path does the any other path you requested actually exist or even if it had permission would it show as 404?

It returns a 404 regardless of whether the file actually exists. It hangs whenever you try to load a directory, regardless of whether the show directory listing or automatically show index.html options are enabled.

**Comment by ethanaobrien** [comment]
It sounds like this is an error with getting the contents of the directory. The index.html option requires the directory contents to have been read. This is possibly because of an error code we are not checking for. Is it possibly you might be able to get that code?

I’ll log all fs errors too when I get all the error catching work done

I also noticed that on windows, if you set the directory to C:/ the path in the UI is all messy. Could you test this (I don’t remember but I’m pretty sure that it does this will all base drives like D:/ E:/ etc)

**Comment by terreng** [comment]
> Is it possibly you might be able to get that code?

Yeah, and it would be easier to do so once all errors are logged and it doesn't just hang.

> I also noticed that on windows, if you set the directory to C:/ the path in the UI is all messy. Could you test this (I don’t remember but I’m pretty sure that it does this will all base drives like D:/ E:/ etc). The path is correct in the backend config, just messed up in the UI

Thanks for bringing this to my attention. I'm not sure how I didn't notice this sooner, but it also messes up paths on macOS. I'll fix it.

In following your instructions to reproduce this issue, I set the path to `C:/` and loaded the URL. I noticed that a few of the files in `C:/` show up as error, which is interesting. I'm not sure how big of an issue this is, but I thought I would mention it.

Screen Shot 2022-06-12 at 12 16 56 PM

**Comment by ethanaobrien** [comment]
I’m pretty sure the errors are a permission thing. I will fix this. It’s not going to error anything that you have access to. I’ll get this done

**Comment by terreng** [comment]
@ethanaobrien We need to add support for macOS **Security-Scoped Bookmarks**. Here's the gist:

Mac App Store apps can't access files/directories unless the user selects that directory in the open dialog. When a user "opens" a directory using the dialog, the app can access all the files in it for as long as it is open. However, when the application is closed, its permissions are reset. So next time you open the app, it won't have permission to read from those directories anymore.

The way to get around this is to use a system called Security-Scoped Bookmarks. When the user first opens a directory, the app receives a _bookmark_, which is a random string, that we can store. Then later when we want to access a file within that directory, we can invoke (access) the bookmark, access the file, and then release it. You can access a bookmark as many times as you want, but you're only supposed to do so right before you access a file, and you must release it right after. Using this system, the app can retain permission to directories even after it is closed.

We must implement this system for the Mac App Store version of the app to work. Here are the steps:

1. When the user selects a file directory, store the bookmark.
2. Immediately before performing any file operations, invoke the appropriate bookmark.
3. Perform the file operation.
4. Release the bookmark.

In my last commit [96bc95d](https://github.com/terreng/simple-web-server/pull/93/commits/96bc95db89a0269cff4aa97a1a363790640baa1e), I implemented the long-term storing of bookmarks, and added a few helper functions that you will need to implement into the file system:

**matchSecurityScopedBookmark(path)**

Given a path, returns the corresponding bookmark string (if it exists). Otherwise null.

**accessSecurityScopedBookmark(bookmark)**

Call this with the bookmark returned from **matchSecurityScopedBookmark** immediately before performing any file operations on that path. It's okay to call this will null, it handles it.

**matchAndAccessSecurityScopedBookmark(path)**

Equivalent to calling **matchSecurityScopedBookmark** with a path, and then calling **accessSecurityScopedBookmark** on the returned bookmark. Returns the bookmark if it exists.

**releaseSecurityScopedBookmark(bookmark)**

Immediately after the file operation has completed, you must call this to release the bookmark. It's okay to call this will null, it'll just do nothing.

According to the Apple documentation: "If you fail to relinquish your access to file-system resources when you no longer need them, your app leaks kernel resources."
So it's super important that all file system calls release the bookmark when they are finished, including if they error.

All of these functions are defined in `index.js` because they require that context. Because `WSC.js` is currently imported via  require, it cannot access these functions. You'll need to pass them in somehow, such as when calling `new WSC.FileSystem`. 

I'm adding a variable defined like so:
```
var bookmarks = {
    match: matchSecurityScopedBookmark,
    matchAndAccess: matchAndAccessSecurityScopedBookmark,
    access: accessSecurityScopedBookmark,
    release: releaseSecurityScopedBookmark
}
```
This way you can pass just the `bookmarks` variable and access the functions like so: `bookmarks.matchAndAccess(path)`

I'll let you decide the best way of implementing this into the existing file system code. Please let me know if you have any questions about how to implement this.

**Comment by ethanaobrien** [comment]
Wow that’s a lot. So basically you want me to add the functions to the FileSystem library, and call the match and access function every time a file is read and release the bookmark when finished reading?

**Comment by terreng** [comment]
> Wow that’s a lot. So basically you want me to add the functions to the FileSystem library, and call the match and access function every time a file is read and release the bookmark when finished reading?

I know, sorry about the information dump. Hopefully it makes sense. I don't think you will find it very difficult to implement. 

Pass the functions into your filesystem code, and then add a `matchAndAccess` and `release` pair around each `fs` call. Make sure `release` is called after the fs call finishes, even with an error. For the read stream in handlers.js, you should call `matchAndAccess` before you create the stream, and then `release` after the stream closes/finishes. 

Here's an example of how you might add the bookmarks code:

```
var bm = bookmarks.matchAndAccess(path);
try {
    var data = fs.readFileSync(path);
} catch(e) {
    bookmarks.release(bm);
    callback({error:err});
    return;
}
bookmarks.release(bm);
callback(data);
```

**Comment by ethanaobrien** [comment]
Ok will do, thanks

**Comment by ethanaobrien** [comment]
@terreng 

with the `this.req.on("close", function() {` issue, I was listening in the wrong place. Changing it to `res.on("close", function() {
` fixed it

**Comment by ethanaobrien** [comment]
@terreng I just left town, won’t be able to do any work for the next week. I’ll still be able to reply.

One thing, on I think line 82 on the console warn reading folder error I accidentally referenced the files variable, which would throw an error, could you please change this reference to the folder variable?

**Comment by terreng** [comment]
@ethanaobrien Looks great! Is there any more work to do with error catching or bookmarks? Or are you all done with that?

**Comment by ethanaobrien** [comment]
Yeah I finished all the error catching and bookmark stuff

**Comment by terreng** [comment]
@ethanaobrien EPERM is the error code that gets raised on Mac when it doesn't have permission to access the directory. Anywhere there's an EPERM error, that should be treated as a 403, not a 404.

Screen Shot 2022-06-14 at 4 21 49 PM

I see you already treat EPERM as a 403 in some places, but for this error it just returns a 404 regardless of what the error code is.

**Comment by terreng** [comment]
I got this error trying to view the directory listing for a path the app didn't have permission to open.

Screen Shot 2022-06-14 at 5 31 05 PM

**Comment by ethanaobrien** [comment]
I’ll update the errors to 403 for that code when I get a chance 

I think I know what the problem is with the directory listing thing. I’ll get those fixed as soon as I’m back

**Comment by ethanaobrien** [comment]
@terreng I fixed the http codes and the directory listing issue. Also, I figured out what was wrong with the tray icon and fixed it. Can you check to see if the tray thingy works on macos?

**Comment by terreng** [comment]
> I fixed the http codes and the directory listing issue. 

Great! I still have a permissions issue left to figure out. Hopefully I'll fix it soon.

> Also, I figured out what was wrong with the tray icon and fixed it. Can you check to see if the tray thingy works on macos?

That's great! I don't have a tray icon when I run it on my mac. I'm going to leave the tray stuff commented out for now, until I have time to work on new features, like that and dark mode.

**Comment by ethanaobrien** [comment]
Sounds good!

**Comment by terreng** [comment]
I just submitted 1.1.4 to app review. As long as this version works and doesn't have any other issues, then this will be our official first release. I'll publish the direct download links to the website too, after I make sure that this version works.

**Comment by terreng** [comment]
1.1.4 was approved and is live on the Mac App Store. I tested everything, and the permissions issue seems to now be completely solved. Hooray!

One more small thing I noticed. Loading a directory listing does now return a 403 when an EPERM is encountered, which is great. However, loading a specific file still returns a 404 when missing read permission, instead of a 403. Could you fix that? It's a minor thing, so we can just include that fix in the next release.

**Comment by terreng** [comment]
> Is this specifically on macos?

I have only tested EPERM error handling on macOS. I don't imagine it's raising any error other than EPERM. Are you sure it handles it? Can you test?

**Comment by ethanaobrien** [comment]
>Version 1.1.4 is now officially released on website for direct download and the Mac App Store! 🎉
It's currently awaiting certification for the Microsoft Store, which shouldn't take more than a day.

Awesome!

>I have only tested EPERM error handling on macOS. I don't imagine it's raising any error other than EPERM. Are you sure it handles it? Can you test?

I just tested, yes windows handles a file with no read permission as a 403 error (if you request a file that does not exist within a directory that does not have read permission it gives you a 404). Not sure why macos isn't. If there is an error reading the file there should be an error in the console. Is it possible you can get me this?

**Comment by terreng** [comment]
Here's the error
Screen Shot 2022-06-20 at 11 31 24 AM

**Comment by ethanaobrien** [comment]
Ah, I think I know what’s wrong. That’s a really strange place for macOS to be throwing the error. I’ll fix when I get the chance

**Comment by terreng** [comment]
When the app doesn't have permission to read from a directory, it doesn't know what files exist within it. So all reads should return a 403, even if the file actually doesn't exist, because it can't know whether it exists.

**Comment by terreng** [comment]
1.1.4 is now approved and on the Microsoft Store!

**Comment by ethanaobrien** [comment]
@terreng Very sorry, I've been really busy lately. Quick question before I fix that one issue. The code checks to make sure that there is a file that is in the directory, this is for windows since it is not case sensitive and could cause security leaks in the htaccess feature. Since mac and linux are case sensitive do you want me to only run this extra step on windows? Let me know what you think and I'll get that fixed.

Also, I think so much has changed in this release that I should probably close #83 and re-submit the pr once I plug everything back in and make sure everything works with the new changes. Should I do this?

**Comment by terreng** [comment]
> Since mac and linux are case sensitive do you want me to only run this extra step on windows?

If it doesn't make a difference on macOS, and it's causing this issue, then removing it for macOS and Linux sounds good to me.

> Also, I think so much has changed in this release that I should probably close https://github.com/terreng/simple-web-server/pull/83 and re-submit the pr once I plug everything back in and make sure everything works with the new changes. Should I do this?

Hold off on that, because I think I have a better idea. I would like to introduce a **plugin system** that would allow people to add additional features to the app, and I would like you to make the first plugin: the proxy plugin. Please take a look at #97 and let me know what you think!

**Comment by terreng** [comment]
@ethanaobrien Simple Web Server now comes up second when you search for "web server" on the Mac App Store!
Screen Shot 2022-07-05 at 6 20 49 PM

It's also now #159 on the charts for top free apps in the developer tools category!
Screen Shot 2022-07-05 at 6 23 32 PM
Screen Shot 2022-07-05 at 6 24 09 PM

**Comment by ethanaobrien** [comment]
Awesome!!

**Pull request merged**
