### PR TITLE
Features

### PR DESCRIPTION
**Pull request by ethanaobrien**
Adds support for array buffer, get file promise functions, better way of reading post and ssjs keys, bug fixes and probably more.

How is the UI coming?

### CODE REVIEW

**Comment by terreng** [comment]
Why do we need an `.npmignore`? 

I just started college, and so I've been pretty busy. I am hoping to have a weekend where I can just work on this a bunch and finish all the UI stuff. 

With Chrome apps going away, I know that this is somewhat time sensitive. I'll try my best to find the time. Thanks for the work that you've done and your patience. Please keep nagging me until I do my part.

**Comment by ethanaobrien** [comment]
>Why do we need an .npmignore?

When packaging the app to distribute, it includes the `dist/` folder which inflates the package. This way we can keep the `dist/` folder and npm won't package it within the app.

>I just started college, and so I've been pretty busy. I am hoping to have a weekend where I can just work on this a bunch and finish all the UI stuff.

Sounds like a good plan!

>With Chrome apps going away, I know that this is somewhat time sensitive. I'll try my best to find the time. Thanks for the work that you've done and your patience. Please keep nagging me until I do my part.

Will do, thank you!

**Comment by ethanaobrien** [comment]
Just letting you know, I cleaned everything in this pr so it is ready!

**Comment by terreng** [comment]
I thought `.npmignore` was for publishing on npm. We're not publishing on npm, are we?

**Comment by ethanaobrien** [comment]
yeah, sorry. Fixed

**Review by terreng — APPROVED** [review]

**Pull request merged**
